#!/bin/sh
# Takes in:
#           repeat ...
# Returns:
#           repeat_...
# And takes in:
#           opt ...
# Returns:
#           opt_...

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 255
elif [ $# -eq 2 ]; then
    cp $1 $2
	perl -pi -w -e 's/repeat statement/repeat_statement/g;' $2
	perl -pi -w -e 's/repeat compound/repeat_compound/g;' $2
	perl -pi -w -e 's/repeat literalOrType/repeat_literalOrType/g;' $2
	perl -pi -w -e 's/repeat literalOrVariable/repeat_literalOrVariable/g;' $2
	perl -pi -w -e 's/repeat barLiteralsAndTypes/repeat_barLiteralsAndTypes/g;' $2
	perl -pi -w -e 's/opt typeRepeater/opt_typeRepeater/g;' $2
else
    echo "Internal tool: use at your own risk! Fixes spaces in XML tag names produced by TXL."
    echo "Usage: fixtxlxml <input> <output>"
    exit 1
fi
