#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 2 ]; then
	echo "Usage: reroot2top <BGF-input> <XBGF-input>"
	exit 1
elif [ ! -r $1 ]; then
	echo "Oops: $1 not found or not readable."
	exit 1
else
	rm -f $2
	if [ `uname` = 'Linux' ] ; then
		xpath -e `cat ${SLPS}/topics/investigation/analysis/listtops.xpath` $1 1> $2.tmp 2> /dev/null
	else
		xpath $1 `cat ${SLPS}/topics/investigation/analysis/listtops.xpath` 1> $2.tmp 2> /dev/null
	fi
	python ${SLPS}/topics/mutation/reroot/reroot2nts.py $2.tmp $2
	rm -f $2.tmp
fi
