#! /bin/sh
# wiki: RetireTs
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
LOCALROOT=${PWD}
cd ${LOCAL1}

if [ $# -ne 2 ]; then
    echo "Usage: striptxbgf <BGF-input> <XBGF-output>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    rm -f $2
    swipl -q -f ${LOCALROOT}/prolog/cli/striptxbgf.pro -- $1 $2
fi
