header("reference-to-copy-library").
header("reference-to-procedure-division-name-format-i").
header("reference-to-procedure-division-name-format-ii").
header("simple-data-reference").
header("identifier-format-i").
header("identifier-format-ii").
header("condition-name-in-data-division").
header("condition-name-in-special-names-paragraph").
header("subscripting").
header("reference-modification").
header("cobol-source-program").
header("nested-source-program").
header("sequence-of-cobol-source-programs").
header("identification-division").
header("program-id-paragraph").
header("environment-division").
header("configuration-section").
header("input-output-section").
header("source-computer-paragraph").
header("object-computer-paragraph").
header("ocp-entry").
header("special-names-paragraph").
header("snp-entry").
header("input-output-section").
header("file-control-paragraph").
header("qsam-sam-vsam-sequential-file-control-entries").
header("vsam-indexed-file-control-entries").
header("idx-entry").
header("vsam-relative-file-control-entries").
header("i-o-control-paragraph").
header("qsam-or-sam-i-o-control-entries").
header("vsam-i-o-control-entries").
header("sort-merge-i-o-control-entries").
header("data-division").
header("fd-entry-sequential-files").
header("seq-clause-a").
header("seq-clause-b").
header("fd-entry-relative-indexed-files").
header("ri-clause").
header("sd-entry-sort-merge-files").
header("sd-clause-a").
header("sd-clause-b").
header("record-clause-format-i").
header("record-clause-format-ii").
header("record-clause-format-iii").
header("data-description-entry-format-i").
header("data-description-entry-format-ii").
header("data-description-entry-format-iii").
header("data-at-level").
header("blank-when-zero-clause").
header("justified-clause").
header("occurs-clause-format-i").
header("occurs-clause-format-ii").
header("picture-clause").
header("redefines-clause").
header("renames-clause").
header("sign-clause").
header("synchronized-clause").
header("usage-clause").
header("value-clause-format-i").
header("value-clause-format-ii").
header("value-clause-format-iii").
header("procedure-division-format-i").
header("sect"). 
header("para"). 
header("procedure-division-format-ii"). 
header("procedure-division-header"). 
header("class-condition"). 
header("condition-name-condition"). 
header("relation-condition"). 
header("comparing-pointer-data-items"). 
header("sign-condition"). 
header("switch-status-condition"). 
header("negated-simple-condition"). 
header("combined-condition"). 
header("abbreviated-combined-relation-condition"). 
header("into-from-identifier-phrase"). 
header("accept-statement-format-i"). 
header("accept-statement-format-ii"). 
header("add-statement-format-i"). 
header("add-statement-format-ii"). 
header("add-statement-format-iii"). 
header("alter-statement"). 
header("call-statement-format-i"). 
header("call-statement-format-ii"). 
header("cancel-statement"). 
header("close-statement-format-i").
header("close-statement-format-ii").
header("compute-statement").
header("continue-statement").
header("delete-statement").
header("display-statement").
header("divide-statement-format-i").
header("divide-statement-format-ii").
header("divide-statement-format-iii").
header("divide-statement-format-iv").
header("divide-statement-format-v").
header("entry-statement").
header("evaluate-statement").
header("e-phrase-a").
header("e-phrase-b").
header("exit-statement").
header("exit-program-statement").
header("goback-statement").
header("go-to-statement-format-i").
header("go-to-statement-format-ii").
header("go-to-statement-format-iii").
header("go-to-statement-format-iv").
header("if-statement").
header("initialize-statement").
header("inspect-statement-format-i").
header("i1-phrase").
header("inspect-statement-format-ii").
header("i2-phrase").
header("inspect-statement-format-iii").
header("i3-phrase").
header("inspect-statement-format-iv").
header("i4-phrase").
header("merge-statement").
header("move-statement-format-i").
header("move-statement-format-ii").
header("multiply-statement-format-i").
header("multiply-statement-format-ii").
header("open-statement-format-i").
header("open-statement-format-ii").
header("perform-statement-format-i").
header("perform-statement-format-ii").
header("perform-statement-format-iii").
header("test-phrase").
header("perform-statement-format-iv").
header("varying-phrase").
header("after-phrase").
header("read-statement-format-i").
header("read-statement-format-ii").
header("release-statement").
header("return-statement").
header("rewrite-statement").
header("search-statement-format-i").
header("search-statement-format-ii").
header("set-statement-format-i").
header("set-statement-format-ii").
header("set-statement-format-iii").
header("set-statement-format-iv").
header("set-statement-format-v").
header("sort-statement").
header("start-statement").
header("stop-statement").
header("string-statement").
header("subtract-statement-format-i").
header("subtract-statement-format-ii").
header("subtract-statement-format-iii").
header("unstring-statement").
header("write-statement-format-i").
header("w-phrase").
header("write-statement-format-ii").
header("write-statement-format-iii").
header("write-statement-format-iv").
header("basis-directive").
header("cbl-process-directive").
header("control-cbl-directive").
header("copy-directive").
header("delete-directive").
header("eject-directive").
header("enter-directive").
header("insert-directive").
header("ready-reset-trace-directive").
header("replace-directive-format-i").
header("replace-directive-format-ii").
header("service-label-directive").
header("service-reload-directive").
header("skip123-directive").
header("title-directive").
header("use-directive-format-i").
header("use-directive-format-ii").
header("use-directive-format-iii").
