build:

test:

clean:
	rm -f *.pyc

generate:
	python /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/libgenerateDS/generateDS.py --no-process-includes -o LDF.py ../xsd/ldf.xsd
	python /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/libgenerateDS/generateDS.py --no-process-includes -o BGF.py ../xsd/bgf.xsd
	python /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/libgenerateDS/generateDS.py --no-process-includes -o XBGF.py ../xsd/xbgf.xsd
