build:

test:
	# generate all test cases for all grammars
	make clean
	make $(patsubst %.bgf,%.test,$(wildcard *.bgf))
	ls *.btf > log
	diff baseline log
	rm log

%.test:
	# generate all test cases for one grammar
	gbtf $*.bgf ${gbtf-options}

show:
	# pretty-print all generated test cases on the screen
	make $(patsubst %.btf,%.show,$(wildcard *.btf))

%.show:
	# pretty-print one test case on the screen
	showt $*.btf

check:
	# validate all generated test cases
	# xmllint --noout --schema ../../../../../shared/xsd/btf.xsd *.btf
	find . -name '*.btf' -print0 | xargs -0 \
		xmllint --noout --schema ../../../../../shared/xsd/btf.xsd

view:
	# view statistics for all test sets
	ls -1 *.bgf | xargs -n1 ../setview

ignore:
	svn propedit svn:ignore .

convert:
	# convert all generated test cases from tree form (BTF) to source code
	find . -name '*.btf' -print0 | xargs -0 -n1 ../conv

execute:
	# run all test sets for which there is a wrapper
	@make $(patsubst %.run,%.execute,$(wildcard *.run))

%.execute:
	# run all test cases in one test set with an existing wrapper
	@ls -1 $*.bgf.*.src | xargs -n1 ./$*.run 

count:
	@/bin/echo -n BGFs:
	@ls *.bgf | wc -l
	@/bin/echo -n BTFs:
	@find . -name '*.btf' | wc -l
	@/bin/echo -n SRCs:
	@find . -name '*.src' | wc -l

clean:
	rm -f log
	rm -f *~
	find . -name '*.btf' -print0 | xargs -0 \
		rm
