build:

test:
	cd basics && make test
	cd coverage && make test
#	cd tescol && make test
#	cd java && make test

clean:
	rm -f *~
	cd basics && make clean
	cd coverage && make clean
#	cd tescol && make clean
#	cd java && make clean
