none:

test:
	swipl -q -f main.pro -- '../../nb/samples/sample1.nb'
	swipl -q -f main.pro -- '../../nb/samples/sample2.nb'
	swipl -q -f main.pro -- '../samples/typed/add2.lambda'
	swipl -q -f main.pro -- '../samples/typed/iseven.lambda'

prompt:
	swipl -f main.pro

