#! /bin/sh
# wiki: ANTLR2BGF
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
LOCAL2=${PWD}
cd ${LOCAL1}
cd `dirname $1`
LOCAL3=${PWD}
cd ${LOCAL1}

if [ $# -ne 2 ]; then
    echo "Usage: antlr2bgf <ANTLR-input> <BGF-output>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    # Build extractor if needed
    cd ${LOCAL2}/../topics/extraction/antlr
    make
    cd ${LOCAL1}
    rm -f $2
    python ${LOCAL2}/../topics/extraction/antlr/antlrstrip.py ${LOCAL3}/`basename $1` $1.stripped
    java -cp ${CLASSPATH}:${LOCAL2}/../download/antlrworks-1.1.7.jar:${LOCAL2}/../topics/extraction/antlr slps.antlr2bgf.Tool $1.stripped $2
fi
