#! /bin/sh
# wiki: AppendXBGF
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
LOCAL2=${PWD}
cd ${LOCAL1}

if [ $# -lt 2 ]; then
    echo "Usage: appendxbgf <XBGF-output> <XBGF-input1> <XBGF-input2> ..."
    exit 1
else
    swipl -q -t "halt(1)" -f ${LOCAL2}/prolog/cli/appendxbgf.pro -- $*
fi
