#! /bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 3 ]; then
    echo "Usage: asfix2btf <ignored> <AsFix-input> <BTF-output>"
    exit 1
elif [ ! -r $2 ]; then
    echo "Oops: $2 not found or not readable."
    exit 1
else
    # Build extractor if needed
    cd ${SLPS}/topics/extraction/asfix2btf
    make build
    cd ${LOCAL1}
    cat $2 | python ${SLPS}/topics/fl/asfsdf/pre.py | sglr -p ${SLPS}/topics/fl/asfsdf/FL.tbl -t > $3.trm
    (echo "main("; cat $3.trm; echo ")" ) | sglr -p ${SLPS}/topics/extraction/asfix2btf/Main.tbl | asfe -e ${SLPS}/topics/extraction/asfix2btf/Main.eqs | unparsePT > $3.tmp
    xsltproc ${SLPS}/shared/xsl/btf2btf.xslt $3.tmp >$3
    rm -f $3.tmp $3.trm
fi

