#! /bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
LOCAL2=${PWD}
cd ${LOCAL1}

if [ $# -lt 2 ]; then
    echo "Usage: bdt <BGF-input1> <BGF-input2> ..."
    exit 1
else
    for i in $*; do
	if [ ! -r $i ]; then
	    echo "Oops: $i not found or not readable."
	    exit 1
	fi
    done
    swipl -q -f ${LOCAL2}/prolog/cli/bdt.pro -- $*
fi
