#!/bin/sh
# wiki: BGF2DMS

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -eq 1 ]; then
    OUTPUT=/dev/stdout
elif [ $# -ne 2 ]; then
    echo "This tool pretty-prints BGF to DMS-specific BNF."
    echo "Usage: bgf2dms <input-bgf-document> [<output-text>]"
    echo "When output file is not specified, stdout is used."
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    OUTPUT=$2
fi

xsltproc ${SLPS}/topics/export/ebnf/bgf2dms.xslt $1> ${OUTPUT}
