#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 1 ]; then
    echo "This tool runs some metrics on a BGF document"
    echo "Usage: bgflc <BGF-input>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    xsltproc ${SLPS}/topics/presentation/metrics/bgf-overview.xslt $1
fi
