#!/bin/sh

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -eq 1 ]; then
    OUTPUT=/dev/stdout
elif [ $# -ne 2 ]; then
    echo "This tool pretty-prints BTF."
    echo "Usage: btf2src <input-btf> [<output-text>]"
    echo "When output file is not specified, stdout is used."
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    OUTPUT=$2
fi

xsltproc ${SLPS}/topics/export/source/btf2source.xslt $1 >BTF2SRC.tmp
awk '{gsub(/[ ]+/," ")}1' BTF2SRC.tmp >$OUTPUT
rm -f BTF2SRC.tmp
