#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
SHARED=${PWD}
cd ${LOCAL1}

if [ $# -ne 3 ]; then
	echo "This tool produces two XBGF transformation chains from the given CBGF scenario"
    echo "Usage: cbgf2xbgf <CBGF-input> <XBGF-forward-execution> <XBGF-reverse-execution>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
	xsltproc ${SHARED}/xsl/cbgf2xbgf-forward.xslt $1 > $2
	xsltproc ${SHARED}/xsl/cbgf2xbgf-reverse.xslt $1 > $3
fi
