#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 1 ]; then
    echo "Usage: checkbgf <bgf-input>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    xmllint --noout --schema ${SLPS}/shared/xsd/bgf.xsd $1
    java -jar ${SLPS}/download/msv/msv.jar ${SLPS}/shared/xsd/bgf.xsd $1
fi
