#! /bin/sh

# Get our hands on the basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
LOCAL2=${PWD}
cd ${LOCAL1}

if [ $# -ne 2 ]; then
    echo "Usage: dcg2bgf <prolog-input> <bgf-output>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    rm -f $2
    swipl -q -f ${LOCAL2}/lib/prolog/dcg2bgf.pro -- $1 $2
fi
