#!/bin/sh

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -ne 2 ]; then
    echo "Processes Extended XBGF and generates normal XBGF."
    echo "Usage: exbgf2xbgf <input-exbgf-document> <output-xbgf-document>"
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
else
	xsltproc ${SLPS}/shared/xsl/exbgf2xbgf.xslt $1 > $2
fi
