#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

# python ${SLPS}/shared/python/xbgf_overview.py $1 $2 $3 >$4
python ${SLPS}/shared/python/exbgf_detailed_overview.py $1 $2 $3 >$5

