#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

${SLPS}/shared/tools/bgf2bnf $1 $1.bnf
python ${SLPS}/topics/presentation/analyses/findHorizontal.py $1.bnf
rm -f $1.bnf

