#!/bin/sh
# wiki: GDTS
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
LOCAL2=${PWD}
cd ${LOCAL1}

if [ $# -lt 2 ]; then
    echo "This is the silent version of Grammar Diff Tool. If you want a verbose one, please use gdt"
    echo "Usage: gdts <BGF-input1> <BGF-input2> ..."
    exit 1
else
    for i in $*; do
	if [ ! -r $i ]; then
	    echo "Oops: $i not found or not readable."
	    exit 1
	fi
    done
    swipl -q -t "halt(1)" -f ${LOCAL2}/prolog/cli/gdt.pro -- $* | grep -v Ok | grep -v Intersection
fi
