#!/bin/sh

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -ne 2 ]; then
    echo "This tool transforms Language Document Format to HyperText Markup Language"
    echo "Usage: ldf2html <input-language-document> <output-hypertext>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    xsltproc ${SLPS}/shared/xsl/ldf2xhtml.xslt $1 | python ${SLPS}/shared/python/closemeta.py > $2
    perl -pi -w -e 's/xmlns:ns0\=\"http:\/\/planet-sl.org\/ldf\" xmlns=\"\"//g;' $2
    perl -pi -w -e 's/---/&#8212;/g;' $2
    perl -pi -w -e 's/--/&#8211;/g;' $2
    perl -pi -w -e 's/\`\`/&#8220;/g;' $2
    perl -pi -w -e "s/\'\'/&#8221;/g;" $2
fi
