#!/bin/sh

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -ne 2 ]; then
    echo "This tool transforms Language Document Format to Portable Document Format"
    echo "Usage: ldf2pdf <input-language-document> <output-pdf>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    sh ${SLPS}/shared/tools/ldf2html $1 $1.html
    xsltproc ${SLPS}/shared/xsl/xhtml2fo.xslt $1.html > $1.fo
    ${SLPS}/download/fop/fop -q $1.fo $2
    rm -f $1.html $1.fo
fi

