#!/bin/sh

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -ne 2 ]; then
    echo "This tool transforms Language Document Format to LaTeX"
    echo "Usage: ldf2tex <input-language-document> <output-tex-document>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    xsltproc ${SLPS}/shared/xsl/ldf2tex.xslt $1 | python ${SLPS}/shared/python/pp_pp.py > $2
fi
