#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 2 ]; then
    echo "This tool generates a test set from an LDF document"
    echo "Usage: $0 <input-language-document> <output-directory>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    python ${SLPS}/topics/extraction/ldf2set/xml2set.py $1 $2
fi
