#!/bin/sh
# wiki: LDF2PDF
LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -ne 2 ]; then
    echo "This tool transforms Language Document Format to Portable Document Format"
    echo "Usage: ldf2pdf <input-language-document> <output-pdf>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    sh ${SLPS}/shared/tools/ldf2tex  $1 $1.tex
    pdflatex -interaction=batchmode $1
    rm -f $1.html $1.fo $1.tex $1.aux $1.log $1.toc
fi

