#!/bin/sh
# wiki: PlotBGF

LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -lt 1 ]; then
    echo "This tool plots a nonterminal dependency graph for a BGF."
    echo "Usage: plotbgf <input-bgf-document> [<ignore-nonterminal> ...]"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
fi

python ${SLPS}/shared/python/bgf_dependency.py $* > $1.dot
dot -Tpdf $1.dot -o `basename $1 .bgf`.pdf
rm -f $1.dot
