#!/bin/sh
# wiki: Rascal2BGF
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -lt 2 ]; then
    echo "This tool produces a BGF grammar from a Rascal grammar"
    echo "Usage:"
    echo "        rsc2bgf <input-rsc> <output-bgf> SL?"
    echo "SL as the last parameter means to use separator lists"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    python ${SLPS}/topics/extraction/rascal/extract.py $*
fi

