#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 3 ]; then
    echo "This script wraps up the ANTLR (java1) evaluator"
    echo "Usage: $0 <context> <input> <yields>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
fi

java -cp ${CLASSPATH}:${SLPS}/topics/fl/java1/javafl.jar -ea TestEvaluator $1 $2 $3
