#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 2 ]; then
    echo "This script wraps up the Prolog (dcg) parser"
    echo "Usage: $0 <input> <output>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
fi

swipl -q -f ${SLPS}/topics/fl/prolog/TestIO.pro -t "main('$1','$2')"
