#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd topics/fl/asfsdf
SDF=${PWD}
cd ${LOCAL1}

if [ $# -ne 1 ]; then
    echo "This script wraps up the XML parser"
    echo "Usage: $0 <input>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
fi

xmllint --noout --schema ${SLPS}/topics/fl/xsd/fl.xsd $1 1> /dev/null 2> /dev/null
