#!/bin/bash

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../../topics/extraction/sdf
XTR=${PWD}
cd ${LOCAL1}

if [ $# -le 1 ]; then
    echo "This extractor gives a BGF for a list of SDF modules"
    echo "Usage: sdf2bgf <SDF-module> [<SDF-module> ...] <BGF-output>"
    exit 1
elif [ -z `which asfe` ] || [ -z `which sglr` ] || [ -z `which unparsePT` ]; then
    echo 'Need these tools in path: sglr, asfe, unparsePT.'
    exit 2
else
    # Build extractor if needed
    cd ${XTR}
    make build
    cd ${LOCAL1}
    echo "main(definition" > _.def
    CX=1
    for i in $* ; do
        if [ $# -gt $CX ]; then
            if [ ! -r $i ]; then
                echo "Oops: $i not found or not readable."
                exit 1
            fi
            cat $i >> _.def
            CX=`expr $CX + 1`
        else
            echo ")" >> _.def
            cat _.def | sglr -p ${XTR}/Main.tbl | asfe -e ${XTR}/Main.eqs | unparsePT > $i
            # a fix for ->
            perl -pi -w -e 's/strcon2chardata\(\"\-\>\"\)/\-\&gt;/g;' $i
            # a fix for =>
            perl -pi -w -e 's/strcon2chardata\(\"\=\>"\)/\=\&gt;/g;' $i
            perl -pi -w -e "s/sqstrcon2chardata\(\'\=\>'\)/\=\&gt;/g;" $i
            # a fix for <:
            perl -pi -w -e 's/strcon2chardata\(\"\<:\"\)/\&lt;:/g;' $i
            # a fix for <=
            perl -pi -w -e 's/strcon2chardata\(\"\<\=\"\)/\&lt;\=/g;' $i
            perl -pi -w -e "s/sqstrcon2chardata\(\'\<\=\'\)/\&lt;\=/g;" $i
            # a fix for <<
            perl -pi -w -e 's/strcon2chardata\(\"\<\<\"\)/\&lt;\&lt;/g;' $i
            # a fix for <<=
            perl -pi -w -e 's/strcon2chardata\(\"\<\<\=\"\)/\&lt;\&lt;\=/g;' $i
            # a fix for >>
            perl -pi -w -e 's/strcon2chardata\(\"\>\>\"\)/\&gt;\&gt;/g;' $i
            # a fix for &=
            perl -pi -w -e 's/strcon2chardata\(\"\&\=\"\)/\&amp;\=/g;' $i
            # a fix for &&
            perl -pi -w -e 's/strcon2chardata\(\"\&\&\"\)/\&amp;\&amp;/g;' $i
            # a fix for >=
            perl -pi -w -e 's/\<terminal\>\>\=\<\/terminal\>/\<terminal\>\&gt;\=\<\/terminal\>/g;' $i
            # a fix for >>=
            perl -pi -w -e 's/\<terminal\>\>\>\=\<\/terminal\>/\<terminal\>\&gt;\&gt;\=\<\/terminal\>/g;' $i
        fi
    done
    rm -f _.def
fi
