#!/bin/sh
# wiki: TokenOverview
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 1 ]; then
    echo "This tool provides a token overview"
    echo "Usage: tokenover <topic>"
    exit 1
else
    /bin/echo "\begin{tabular}{l|c|c|c|}"
    /bin/echo "&\textit{italic}&\texttt{fixed}&default\\\\\hline"
    /bin/echo -n "\\tokenAlNum&N ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "ITA NONW ALNUM"
    /bin/echo -n ") &T ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "FIX NONW ALNUM"
    /bin/echo -n ")&T? ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "DEF NONW ALNUM"
    /bin/echo ")\\\\"
    /bin/echo -n "\\tokenBar&M ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "ITA NONW BNBAR"
    /bin/echo -n ") &T ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "FIX NONW BNBAR"
    /bin/echo -n ")&M? ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "DEF NONW BNBAR"
    /bin/echo ")\\\\"
    /bin/echo -n "\\tokenMeta&M ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "ITA NONW METAS"
    /bin/echo -n ") &T ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "FIX NONW METAS"
    /bin/echo -n ")&T? ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "DEF NONW METAS"
    /bin/echo ")\\\\"
    /bin/echo -n "\\tokenOther&T ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "ITA WEIRD"
    /bin/echo -n ") &T ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "FIX WEIRD"
    /bin/echo -n ")&T ("
    cd ${SLPS}/topics/$1 ; make debug | grep -c "DEF WEIRD"
    /bin/echo ")\\\\"
    /bin/echo "\hline\end{tabular}"
fi
