#!/bin/sh
# wiki: TXL2BGF
LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
elif [ $# -eq 2 ]; then
	OUTPUT=$2
elif [ $# -eq 1 ]; then
	OUTPUT=${LOCAL}/`basename $1 .txl`.bgf
else
    echo "This tool extracts a BGF grammar from a TXL grammar"
    echo "Usage: txl2bgf <txl-grammar> [<output-grammar>]"
    exit 2
fi

txl $1 ${SLPS}/topics/grammars/metasyntax/txl/TXLGrammar/Txl/txl.txl -xml > grammar.xml
# an ugly fix for strange characters (namely, vertical form feed)
perl -pi -w -e 's// /g;' grammar.xml
#`dirname $0`/../internals/fixtxlxml grammar.xml grammar2.xml
xsltproc ${SLPS}/topics/extraction/txl/txl2bgf.xslt grammar.xml > tmp.bgf
xsltproc ${SLPS}/topics/transformation/normalization/subdefs/inline.xslt tmp.bgf > tmp.xbgf
diff tmp.xbgf `dirname $0`/../internals/empty.xbgf > /dev/null
if [ "$?" -ne "0" ]; then
	${SLPS}/shared/tools/xbgf tmp.xbgf tmp.bgf ${OUTPUT}
else
	cp tmp.bgf ${OUTPUT}
fi
rm -f tmp.bgf tmp.xbgf grammar.xml
