#!/bin/sh
# wiki: validate
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 2 ]; then
	echo "SLPS general validation tool"
    echo "Usage: validate <format> <input>"
    exit 1
elif [ ! -r $2 ]; then
    echo "Oops: $2 not found or not readable."
    exit 1
elif [ $1 == 'txl' ]; then
	txl $2 ${SLPS}/topics/extraction/txl/TXLGrammar/Txl/txl.txl
elif [ $1 == 'btf' ]; then
    xmllint --noout --schema ${SLPS}/shared/xsd/$1.xsd $2
    swipl -q -f ${SLPS}/shared/prolog/cli/checkbtf.pro -- $2
elif [ ! -r ${SLPS}/shared/xsd/$1.xsd ]; then
    echo "Oops: schema for $1 not found or not readable."
    exit 1
else
    xmllint --noout --schema ${SLPS}/shared/xsd/$1.xsd $2
fi
