#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 1 ]; then
    echo "This tool runs some metrics on a XBGF document"
    echo "Usage: xbgfi <BGF-input>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    /bin/echo -n "Correcting: "
    grep -c CORRECT $1
    /bin/echo -n "Extending: "
    grep -c EXTEND $1
    /bin/echo -n "Refactoring: "
    grep -c REFACTOR $1
fi
