#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

python ${SLPS}/topics/presentation/metrics/xbgf_overview.py $1 $2 $3 >$4
python ${SLPS}/topics/presentation/metrics/xbgf_detailed_overview.py $1 $2 $3 >$5

