#!/bin/sh
# wiki: XBGF2TeX
LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -eq 1 ]; then
    OUTPUT=/dev/stdout
elif [ $# -ne 2 ]; then
    echo "This tool transforms Transformational BGF documents to includable TeX files."
    echo "Usage: xbgf2tex <input-xbgf-document> [<output-tex>]"
    echo "When output file is not specified, stdout is used."
    exit 1
else
    OUTPUT=$2
fi
if [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
fi

echo '\\begin{graybox}' > ${OUTPUT}
echo '\\begin{lstlisting}[language=pp]' >> ${OUTPUT}
xsltproc ${SLPS}/shared/xsl/xbgf2xbnf.xslt $1 >> ${OUTPUT}
echo '\\end{lstlisting}' >> ${OUTPUT}
echo '\\end{graybox}' >> ${OUTPUT}
