#!/bin/sh

# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL1}

if [ $# -ne 1 ]; then
    echo "This tool runs some metrics on a XBGF document"
    echo "Usage: xbgfi <BGF-input>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    /bin/echo -n "Number of lines: "
    wc -l $1 | awk '{print $1}'
    /bin/echo -n "Number of transformations: "
	if [ `uname` == "Linux" ] ; then
        xpath -e `cat ${SLPS}/topics/presentation/metrics/transformations.xpath` $1 2> /dev/null
    else
        xpath $1 `cat ${SLPS}/topics/presentation/metrics/transformations.xpath` 2> /dev/null
	fi
    /bin/echo -n "Number of unsafe optimizations: "
    grep -c BREFACTOR $1
    /bin/echo -n "Number of issues (1): "
    grep -c ISSUE $1
    /bin/echo -n "Number of issues (2): "
    expr `grep -c EXTRACTERROR $1` + `grep -c CORRECT $1` + `grep -c EXTEND $1` + `grep -c PERMISSIVENESS $1`
    /bin/echo -n "  post-extraction: "
    grep -c EXTRACTERROR $1
    /bin/echo -n "  correction: "
    grep -c CORRECT $1
    /bin/echo -n "  extending: "
    grep -c EXTEND $1
    /bin/echo -n "  permissiveness: "
    grep -c PERMISSIVENESS $1
fi

