#! /bin/sh
# wiki: XSD2BGF
# Get our hands on basedir
LOCAL1=${PWD}
cd `dirname $0`
cd ..
LOCALROOT=${PWD}
cd ${LOCAL1}

if [ $# -lt 2 ]; then
    echo "Usage: xsd2bgf <XSD-input> <BGF-output>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
fi

rm -f $2

if [ -$3 == '---noimport' ]; then
    swipl -q -f ${LOCALROOT}/prolog/cli/onexsd2bgf.pro -- $1 $2
else
    swipl -q -f ${LOCALROOT}/prolog/cli/xsd2bgf.pro -- $1 $2
fi
