#! /bin/sh

# Get our hands on the languedoc basedir
LOCAL=${PWD}
cd `dirname $0`
cd ../..
SLPS=${PWD}
cd ${LOCAL}

if [ $# -ne 2 ]; then
    echo "This tool transforms XML Schema Definition to Language Document Format"
    echo "Usage: xsd2ldf <input-schema> <output-language-document>"
    exit 1
elif [ ! -r $1 ]; then
    echo "Oops: $1 not found or not readable."
    exit 1
else
    rm -f $2
    sh ${SLPS}/shared/tools/xsd2bgf $1 $2.bgf
    python ${SLPS}/shared/python/xsd2ldf.py $1 $2.bgf $2
    rm -f $2.bgf
fi

