#!/bin/sh

if [ $3 == 'jls1-impl' ]; then
	cp ../topics/grammars/$2/jls1/extracted-implementable-grammar.bgf $1/$2/$3.bgf
elif [ $3 == 'jls2-impl' ]; then
	cp ../topics/grammars/$2/jls2/extracted-implementable-grammar.bgf $1/$2/$3.bgf
elif [ $3 == 'jls3-impl' ]; then
	cp ../topics/grammars/$2/jls3/extracted-implementable-grammar.bgf $1/$2/$3.bgf
elif [ $3 == 'jls1-read' ]; then
	cp ../topics/grammars/$2/jls1/extracted-readable-grammar.bgf $1/$2/$3.bgf
elif [ $3 == 'jls2-read' ]; then
	cp ../topics/grammars/$2/jls2/extracted-readable-grammar.bgf $1/$2/$3.bgf
elif [ $3 == 'jls3-read' ]; then
	cp ../topics/grammars/$2/jls3/extracted-readable-grammar.bgf $1/$2/$3.bgf
elif [ $2 == 'java' ]; then
	cp ../topics/grammars/$2/antlr-java-5/$3/$3.bgf $1/$2/$3.bgf
elif [ $3 == 'iso-23270-2003' ]; then
	cp ../topics/grammars/$2/iso-23270-2003/$2.ext.bgf $1/$2/$3.bgf
elif [ $3 == 'iso-23270-2003-recovered' ]; then
	cp ../topics/grammars/$2/iso-23270-2003/$2.bgf $1/$2/$3.bgf
elif [ $2 == 'metasyntax' ]; then
	cp ../topics/grammars/$2/$3/$3.bgf $1/$2/$3.bgf
else
    cp ../topics/grammars/$2/$3/$2.bgf $1/$2/$3.bgf
fi
