#!/bin/sh

../shared/tools/bgf2bnf   $1/$2.bgf $1/$2.bnf
../shared/tools/bgf2dms   $1/$2.bgf $1/$2.dms
../shared/tools/bgf2sdf   $1/$2.bgf $1/$2.sdf
../shared/tools/bgf2rsc   $1/$2.bgf $1/$2.rsc
../topics/investigation/analysis/overview_bgf.py $1/$2.bgf >tmp.xml || exit -1
xsltproc --stringparam date `date +"%d/%m/%Y"` --stringparam zoo ../../../www/_dev/$1.xml --stringparam id $3 --stringparam report ../../../www/tmp.xml ../topics/export/hypertext/bgf2fancy.xslt $1/$2.bgf >$1/$2.html || exit -1
if [ -r ../topics/grammars/$3 ]; then
	ls -1 ../topics/grammars/$3/*.xbgf | xargs -n1 -I _ basename _ .xbgf | xargs -n1 -I _ ../shared/tools/xbgf2html ../topics/grammars/$3/_.xbgf $1/$2-_.html `basename $2`.html
fi
