#!/bin/sh

../shared/tools/bgf2bnf   zoo/$1/$2.bgf zoo/$1/$2.bnf
../shared/tools/bgf2dms   zoo/$1/$2.bgf zoo/$1/$2.dms
../shared/tools/bgf2sdf   zoo/$1/$2.bgf zoo/$1/$2.sdf
../shared/tools/bgf2rsc   zoo/$1/$2.bgf zoo/$1/$2.rsc
if [ $2 == 'iso-23270-2003-recovered' ]; then
	_dev/fancy zoo $1 $2 csharp-iso-23270-2003
elif [ $2 == 'jls1-read' ]; then
	_dev/fancy zoo $1 $2 jls1
elif [ $2 == 'jls2-read' ]; then
	_dev/fancy zoo $1 $2 jls2
elif [ $2 == 'jls3-read' ]; then
	_dev/fancy zoo $1 $2 jls3
elif [ $2 == 'jls1-impl' ]; then
	_dev/fancy zoo $1 $2 jls1
elif [ $2 == 'jls2-impl' ]; then
	_dev/fancy zoo $1 $2 jls2
elif [ $2 == 'jls3-impl' ]; then
	_dev/fancy zoo $1 $2 jls3
elif [ $1 == 'java' ]; then
	_dev/fancy zoo $1 $2 $1-$2
	ls -1 ../topics/grammars/$1/antlr-java-5/$2/*.xbgf | xargs -n1 -I _ basename _ .xbgf | xargs -n1 -I _ ../shared/tools/xbgf2html ../topics/grammars/$1/antlr-java-5/$2/_.xbgf zoo/$1/$2-_.html $2.html
elif [ -r ../topics/grammars/$1/$2 ]; then
	_dev/fancy zoo $1 $2 $1-$2
	ls -1 ../topics/grammars/$1/$2/*.xbgf | xargs -n1 -I _ basename _ .xbgf | xargs -n1 -I _ ../shared/tools/xbgf2html ../topics/grammars/$1/$2/_.xbgf zoo/$1/$2-_.html $2.html
else
	echo Cannot find directory $1/$2
	exit -1
fi
