#!/bin/sh

echo '[Test Case]' `basename $1`
python export.py $1 py.bnf
xsltproc ../../../shared/xsl/bgf2bnf.xslt $1 > xsl.bnf
diff py.bnf xsl.bnf
if [ $? -ne 0 ]; then
	echo 'ERROR. Python vs XSLT output follows:'
	cat py.bnf
	cat xsl.bnf
    exit -1
fi