all:
	@echo Run 'make rebuild' if you want to renew the sources from their URLs.
	@echo NOT recommended UNLESS you really know what you are doing!

rebuild:
	curl -k http://java.sun.com/docs/books/jls/first_edition/html/19.doc.html > jls1/syntax.html
	curl -k http://java.sun.com/docs/books/jls/second_edition/html/syntax.doc.html > jls2/syntax.html
	curl -k http://java.sun.com/docs/books/jls/third_edition/html/syntax.html > jls3/syntax.html

