build:
	cd prolog; make build
	cd tools; make build
	cd xsd; make build
	cd xsl; make build

test:
	cd prolog; make test
	cd tools; make test
	cd xsd; make test
	cd xsl; make test

clean:
	cd prolog; make clean
	cd tools; make clean
	cd xsd; make clean
	cd xsl; make clean
