#!/bin/sh

# m2 file.mbgf one two
# $0    $1     $2  $3
./mbgf2xbgf.py $1 $2 $3 tmp.xbgf
xbgf tmp.xbgf `xpath $1 'mbgf:sequence/sources/src[@name="'$2'"]/text()' 2> /dev/null` tmp1.bgf
gdts tmp1.bgf `xpath $1 'mbgf:sequence/sources/src[@name="'$3'"]/text()' 2> /dev/null`
rm tmp.xbgf
./mbgf2xbgf.py $1 $3 $2 tmp.xbgf
xbgf tmp.xbgf `xpath $1 'mbgf:sequence/sources/src[@name="'$3'"]/text()' 2> /dev/null` tmp2.bgf
gdts tmp2.bgf `xpath $1 'mbgf:sequence/sources/src[@name="'$2'"]/text()' 2> /dev/null`
# m2 file.mbgf 1 one.bgf 2 two.bgf
# $0    $1    $2    $3   $4    $5
# ./mbgf2xbgf.py $1 $2 $4 tmp.xbgf
# xbgf tmp.xbgf $3 $3.tmp
# gdts $3.tmp $5
# rm tmp.xbgf
# ./mbgf2xbgf.py $1 $4 $2 tmp.xbgf
# xbgf tmp.xbgf $5 $5.tmp
# gdts $5.tmp $3
