build:
	cd dcg2bgf; make build
	cd java2bgf; make build
	cd xsd2bgf; make build

test:
	cd dcg2bgf; make test
	cd java2bgf; make test
	cd xsd2bgf; make test

clean:
	cd dcg2bgf; make clean
	cd java2bgf; make clean
	cd xsd2bgf; make clean

