build:
	cd antlr2bgf; make build
	cd asfix2btf; make build
	cd dcg2bgf; make build
	cd java2bgf; make build
	cd ldf2bgf; make build
	cd ldf2pdf; make build
	cd sdf2bgf; make build
	cd xml2btf; make build
	cd xsd2bgf; make build
	cd xsd2ldf; make build

test:
	cd antlr2bgf; make test
	cd asfix2btf; make test
	cd dcg2bgf; make test
	cd java2bgf; make test
	cd ldf2bgf; make test
	cd ldf2pdf; make test
	cd sdf2bgf; make test
	cd xml2btf; make test
	cd xsd2bgf; make test
	cd xsd2ldf; make test

clean:
	cd antlr2bgf; make clean
	cd asfix2btf; make clean
	cd dcg2bgf; make clean
	cd java2bgf; make clean
	cd ldf2bgf; make clean
	cd ldf2pdf; make clean
	cd sdf2bgf; make clean
	cd xml2btf; make clean
	cd xsd2bgf; make clean
	cd xsd2ldf; make clean
