build:
	cd xbgf ; make build
	cd bgf ; make build
	cd xldf ; make build
	cd ldf ; make build
	cd lcf ; make build

rebuild:
	cd xbgf ; make rebuild
	cd bgf ; make rebuild
	cd xldf ; make rebuild
	cd ldf ; make rebuild

clean:
	cd xbgf ; make clean
	cd bgf ; make clean
	cd xldf ; make clean
	cd ldf ; make clean

