none:

test:
	swipl -q -f main.pro -- '../../nb/samples/sample1.nb'
	swipl -q -f main.pro -- '../../nb/samples/sample2.nb'
	swipl -q -f main.pro -- '../../lambda/samples/typed/add2.lambda'
	swipl -q -f main.pro -- '../../lambda/samples/typed/iseven.lambda'
	swipl -q -f main.pro -- '../samples/trivial.fun'
	swipl -q -f main.pro -- '../samples/add.fun'
	swipl -q -f main.pro -- '../samples/mult.fun'
	swipl -q -f main.pro -- '../samples/factorial.fun'

prompt:
	swipl -f main.pro

