//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="fl")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="fl", IsNullable=false)]
public partial class Program {
    
    private Function[] functionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("function")]
    public Function[] function {
        get {
            return this.functionField;
        }
        set {
            this.functionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
public partial class Function {
    
    private string nameField;
    
    private string[] argField;
    
    private Expr rhsField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("arg")]
    public string[] arg {
        get {
            return this.argField;
        }
        set {
            this.argField = value;
        }
    }
    
    /// <remarks/>
    public Expr rhs {
        get {
            return this.rhsField;
        }
        set {
            this.rhsField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Apply))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IfThenElse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Binary))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Argument))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Literal))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
[System.Xml.Serialization.XmlRootAttribute("Fragment", Namespace="fl", IsNullable=false)]
public abstract partial class Expr {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
public partial class Apply : Expr {
    
    private string nameField;
    
    private Expr[] argField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("arg")]
    public Expr[] arg {
        get {
            return this.argField;
        }
        set {
            this.argField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
public partial class IfThenElse : Expr {
    
    private Expr ifExprField;
    
    private Expr thenExprField;
    
    private Expr elseExprField;
    
    /// <remarks/>
    public Expr ifExpr {
        get {
            return this.ifExprField;
        }
        set {
            this.ifExprField = value;
        }
    }
    
    /// <remarks/>
    public Expr thenExpr {
        get {
            return this.thenExprField;
        }
        set {
            this.thenExprField = value;
        }
    }
    
    /// <remarks/>
    public Expr elseExpr {
        get {
            return this.elseExprField;
        }
        set {
            this.elseExprField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
public partial class Binary : Expr {
    
    private Ops opsField;
    
    private Expr leftField;
    
    private Expr rightField;
    
    /// <remarks/>
    public Ops ops {
        get {
            return this.opsField;
        }
        set {
            this.opsField = value;
        }
    }
    
    /// <remarks/>
    public Expr left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    public Expr right {
        get {
            return this.rightField;
        }
        set {
            this.rightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
public enum Ops {
    
    /// <remarks/>
    Equal,
    
    /// <remarks/>
    Plus,
    
    /// <remarks/>
    Minus,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
public partial class Argument : Expr {
    
    private string nameField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="fl")]
public partial class Literal : Expr {
    
    private int infoField;
    
    /// <remarks/>
    public int info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
}
