build:
	cd bgf; make build
	cd xbgf; make build
	cd btf; make build
	cd lcf; make build

rebuild:
	make clean
	make build

test:
	cd bgf; make test
	cd xbgf; make test
	cd btf; make test
	cd lcf; make test

clean:
	rm -f *~
	cd bgf; make clean
	cd xbgf; make clean
	cd btf; make clean
	cd lcf; make clean

